import numpy as np
    
def fun_1_0(A = None,B = None,seta_o = None): 
    #FUN_1_0
#    EQN_2 = FUN_1_0(SETA_C2U,A,B,SETA_O)
    
    #    This function was generated by the Symbolic Math Toolbox version 8.1.
#    09-Jan-2021 01:07:16
    
    # t2 = 1.0./B;
# t3 = seta_o-seta_C2U;
# t4 = (1.0./B).*(seta_o-seta_C2U);
    eqn_2 = lambda seta_C2U = None: np.multiply(np.multiply(A,np.exp(np.multiply((1.0 / B),(seta_o - seta_C2U)))),((np.multiply((1.0 / B),(seta_o - seta_C2U))) + 1.0))
    return eqn_2