import numpy as np
    
def fun_1(PL = None,f = None,h_dlta_TUAV_UAV = None,seta_3db = None,Go = None): 
    #FUN_1
#    EQN_3 = FUN_1(SETA_TUAV2UAV,PL,F,H_DLTA_TUAV_UAV,SETA_3DB,GO)
    
    #    This function was generated by the Symbolic Math Toolbox version 8.1.
#    06-Jan-2021 16:24:28
    
    t2 = np.log(10.0)
    t3 = 1.0 / t2
    eqn_3 = lambda seta_TUAV2UAV = None: np.multiply(Go,- 2.0) - PL + 1.0 / seta_3db ** 2.0 * seta_TUAV2UAV ** 2.0 * 24.0 + np.multiply(np.multiply(t3,np.log(f)),20.0) + np.multiply(np.multiply(t3,np.log(h_dlta_TUAV_UAV)),20.0) - np.multiply(np.multiply(t3,np.log(np.sin(np.multiply(np.multiply(seta_TUAV2UAV,np.pi),(1.0 / 180.0))))),20.0) - 295.0 / 2.0
    return eqn_3