import numpy as np
    
def fun_6(PL = None,f = None,seta_TUAV2UAV_C = None,Go = None,seta_3db = None): 
    #FUN_6
#    EQN_3 = FUN_6(H_DLTA,PL,F,SETA_TUAV2UAV_C,GO,SETA_3DB)
    
    #    This function was generated by the Symbolic Math Toolbox version 8.1.
#    06-Jan-2021 18:19:52
    
    t2 = np.log(10.0)
    t3 = 1.0 / t2
    eqn_3 = lambda h_dlta = None: np.multiply(Go,- 2.0) - PL + 1.0 / seta_3db ** 2.0 * seta_TUAV2UAV_C ** 2.0 * 24.0 + np.multiply(np.multiply(t3,np.log(f)),20.0) + np.multiply(np.multiply(t3,np.log(h_dlta)),20.0) - np.multiply(np.multiply(t3,np.log(np.sin(np.multiply(np.multiply(seta_TUAV2UAV_C,np.pi),(1.0 / 180.0))))),20.0) - 295.0 / 2.0
    return eqn_3