import numpy as np
    
def fun_5(seta_3db = None): 
    #FUN_5
#    EQN_6 = FUN_5(SETA_H,SETA_3DB)
    
    #    This function was generated by the Symbolic Math Toolbox version 8.1.
#    06-Jan-2021 18:15:13
    
    eqn_6 = lambda seta_h = None: np.multiply(seta_h,1.0) / seta_3db ** 2.0 * 48.0 - 0.1516908212560386 / np.tan(np.multiply(np.multiply(seta_h,np.pi),(1.0 / 180.0)))
    return eqn_6